//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
    }
}
