//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casting
    {
        public Casting()
        {
            this.CreditNoteLineItem = new HashSet<CreditNoteLineItem>();
            this.DailyProductionPerformance = new HashSet<DailyProductionPerformance>();
            this.InvoiceLineItem = new HashSet<InvoiceLineItem>();
            this.Quotation = new HashSet<Quotation>();
            this.PurchaseOrderLineItems = new HashSet<PurchaseOrderLineItems>();
            this.SpecialCasting = new HashSet<SpecialCasting>();
            this.StockTakeLineItem = new HashSet<StockTakeLineItem>();
            this.StockTakeVarianceLineItem = new HashSet<StockTakeVarianceLineItem>();
            this.WeeklyPlan = new HashSet<WeeklyPlan>();
        }
    
        public int CastingID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public string Customer { get; set; }
        public string DieOwnership { get; set; }
        public Nullable<decimal> Standard { get; set; }
        public Nullable<decimal> FettlerStandard { get; set; }
        public Nullable<decimal> Cavity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> RunnerWeight { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Sandblasting { get; set; }
        public Nullable<decimal> CoreMaking { get; set; }
        public Nullable<decimal> CoreRemoval { get; set; }
        public Nullable<decimal> WeightCore { get; set; }
        public Nullable<int> NumberOfCasters { get; set; }
        public Nullable<int> PrefferedTable { get; set; }
        public string PrefferedFurnace { get; set; }
        public Nullable<int> PrefferedCaster1 { get; set; }
        public Nullable<int> PrefferedCaster2 { get; set; }
        public Nullable<int> PrefferedCaster3 { get; set; }
        public Nullable<int> DieID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<decimal> SandCost { get; set; }
        public Nullable<decimal> GlueCost { get; set; }
        public Nullable<decimal> CoreMakerCost { get; set; }
        public Nullable<decimal> CoreRemoverCost { get; set; }
        public Nullable<decimal> SandUsed { get; set; }
        public Nullable<decimal> GlueUsed { get; set; }
        public Nullable<decimal> TotalSandCost { get; set; }
        public Nullable<decimal> DrillingCost { get; set; }
        public Nullable<decimal> TappingCost { get; set; }
        public Nullable<decimal> TurningCost { get; set; }
        public Nullable<decimal> MillingCost { get; set; }
        public Nullable<decimal> ThreadingCost { get; set; }
        public Nullable<decimal> TotalMachineryCost { get; set; }
        public Nullable<int> InventoryUnitsOnHand { get; set; }
        public Nullable<int> InventoryUnitsOnHandWithRunners { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Alloy Alloy { get; set; }
        public virtual ICollection<CreditNoteLineItem> CreditNoteLineItem { get; set; }
        public virtual ICollection<DailyProductionPerformance> DailyProductionPerformance { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItem { get; set; }
        public virtual ICollection<Quotation> Quotation { get; set; }
        public virtual ICollection<PurchaseOrderLineItems> PurchaseOrderLineItems { get; set; }
        public virtual ICollection<SpecialCasting> SpecialCasting { get; set; }
        public virtual ICollection<StockTakeLineItem> StockTakeLineItem { get; set; }
        public virtual ICollection<StockTakeVarianceLineItem> StockTakeVarianceLineItem { get; set; }
        public virtual ICollection<WeeklyPlan> WeeklyPlan { get; set; }
    }
}
