//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProductionPerformance
    {
        public long DailProductionPerformanceID { get; set; }
        public string ShiftNo { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public int EmployeeID { get; set; }
        public string Pot { get; set; }
        public int PerformancePercentage { get; set; }
        public decimal Standard { get; set; }
        public Nullable<int> Total9 { get; set; }
        public Nullable<int> Scrap9 { get; set; }
        public Nullable<int> Total11 { get; set; }
        public Nullable<int> Scrap11 { get; set; }
        public Nullable<int> Total13 { get; set; }
        public Nullable<int> Scrap13 { get; set; }
        public Nullable<int> Total15 { get; set; }
        public Nullable<int> Scrap15 { get; set; }
        public Nullable<int> Total16 { get; set; }
        public Nullable<int> Scrap16 { get; set; }
        public Nullable<int> TotalTotal { get; set; }
        public Nullable<int> TotalScrap { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ScrapFettling { get; set; }
        public Nullable<int> ScrapDrillingAndT { get; set; }
        public Nullable<int> ScrapQCBefore { get; set; }
        public Nullable<int> ScrapQCMandla { get; set; }
        public Nullable<decimal> CastingWeight { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> ScrapManufacturing { get; set; }
        public Nullable<int> ShiftTypeModifier { get; set; }
        public Nullable<int> ShiftTypeId { get; set; }
        public Nullable<decimal> AdjustedStandard { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Casting Casting { get; set; }
    }
}
