//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public DeliveryNote()
        {
            this.DeliveryNoteLineItem = new HashSet<DeliveryNoteLineItem>();
        }
    
        public long DeliveryNoteID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string SupplierInvoiceNo { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual ICollection<DeliveryNoteLineItem> DeliveryNoteLineItem { get; set; }
    }
}
