//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WahlEntities : DbContext
    {
        public WahlEntities()
            : base("name=WahlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Alloy> Alloy { get; set; }
        public DbSet<Casting> Casting { get; set; }
        public DbSet<CastingCodedelete> CastingCodedelete { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<Consumable> Consumable { get; set; }
        public DbSet<CreditNote> CreditNote { get; set; }
        public DbSet<CreditNoteLineItem> CreditNoteLineItem { get; set; }
        public DbSet<DailyProductionPerformance> DailyProductionPerformance { get; set; }
        public DbSet<Day> Day { get; set; }
        public DbSet<DeliveryNote> DeliveryNote { get; set; }
        public DbSet<DeliveryNoteLineItem> DeliveryNoteLineItem { get; set; }
        public DbSet<Die> Die { get; set; }
        public DbSet<DieOwnership> DieOwnership { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<ExternalCustomer> ExternalCustomer { get; set; }
        public DbSet<Inventory> Inventory { get; set; }
        public DbSet<InventoryGroup> InventoryGroup { get; set; }
        public DbSet<InventoryType> InventoryType { get; set; }
        public DbSet<Invoice> Invoice { get; set; }
        public DbSet<InvoiceLineItem> InvoiceLineItem { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Month> Month { get; set; }
        public DbSet<MonthlyAlloyCost> MonthlyAlloyCost { get; set; }
        public DbSet<MonthlyExpense> MonthlyExpense { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public DbSet<PurchaseOrderLineItems> PurchaseOrderLineItems { get; set; }
        public DbSet<Quotation> Quotation { get; set; }
        public DbSet<ReturnToSupplier> ReturnToSupplier { get; set; }
        public DbSet<RolePermission> RolePermission { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Sample> Sample { get; set; }
        public DbSet<SearchField> SearchField { get; set; }
        public DbSet<SearchType> SearchType { get; set; }
        public DbSet<SpecialCasting> SpecialCasting { get; set; }
        public DbSet<StockTake> StockTake { get; set; }
        public DbSet<StockTakeLineItem> StockTakeLineItem { get; set; }
        public DbSet<StockTakeVarianceLineItem> StockTakeVarianceLineItem { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<SupplierType> SupplierType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<temp_DataSource> temp_DataSource { get; set; }
        public DbSet<temp_Reports> temp_Reports { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WeeklyPlan> WeeklyPlan { get; set; }
        public DbSet<Year> Year { get; set; }
    }
}
