//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyExpense
    {
        public MonthlyExpense()
        {
            this.MonthlyAlloyCost = new HashSet<MonthlyAlloyCost>();
        }
    
        public int MonthlyExpensesID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> TotalGas { get; set; }
        public Nullable<decimal> TotalElectricity { get; set; }
        public Nullable<decimal> TotalWater { get; set; }
        public Nullable<decimal> MachineryService { get; set; }
        public Nullable<decimal> Labour { get; set; }
        public Nullable<decimal> SafetyClothing { get; set; }
        public Nullable<decimal> TotalStandardMonthlyCosts { get; set; }
        public Nullable<decimal> CastingStdPercentagePerDay { get; set; }
        public Nullable<decimal> CasterPerDay { get; set; }
        public Nullable<decimal> FettlerPerDay { get; set; }
        public Nullable<decimal> SandBlasterPerDay { get; set; }
        public Nullable<decimal> SandCoreMakerPerDay { get; set; }
        public Nullable<decimal> SandCoreRemoverPerDay { get; set; }
        public Nullable<decimal> GeneralExpenses { get; set; }
        public Nullable<decimal> TotalLabourCosts { get; set; }
        public Nullable<decimal> MetalLM4PerKg { get; set; }
        public Nullable<decimal> MetalLM6PerKg { get; set; }
        public Nullable<decimal> MetalLM9PerKg { get; set; }
        public Nullable<decimal> MetalLM25PerKg { get; set; }
        public Nullable<decimal> MetalZincPerKg { get; set; }
        public Nullable<decimal> CostOfSandPerKg { get; set; }
        public decimal GasAt { get; set; }
        public decimal ElectricityAt { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
    
        public virtual ICollection<MonthlyAlloyCost> MonthlyAlloyCost { get; set; }
    }
}
