//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyAlloyCost
    {
        public long MonthlyAlloyCostID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
    
        public virtual Alloy Alloy { get; set; }
        public virtual MonthlyExpense MonthlyExpense { get; set; }
    }
}
