//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderLineItems
    {
        public long PurchaseOrderLineItemID { get; set; }
        public Nullable<int> Ordered { get; set; }
        public Nullable<int> QuantityUnit { get; set; }
        public Nullable<decimal> PriceExDiscount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalExcl { get; set; }
        public Nullable<decimal> TotalIncl { get; set; }
    
        public virtual Casting Casting { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
