//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.InvoiceLineItem = new HashSet<InvoiceLineItem>();
            this.Quotation = new HashSet<Quotation>();
            this.PurchaseOrderLineItems = new HashSet<PurchaseOrderLineItems>();
            this.WeeklyPlan = new HashSet<WeeklyPlan>();
        }
    
        public int PurchaseOrderID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string TaxRegistrationNumber { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string ContactName { get; set; }
        public string From { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ExternalReference { get; set; }
        public string OrderPlacedBy { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string OrderID { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Signed { get; set; }
        public Nullable<decimal> TotalExcl { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalIncl { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItem { get; set; }
        public virtual ICollection<Quotation> Quotation { get; set; }
        public virtual ICollection<PurchaseOrderLineItems> PurchaseOrderLineItems { get; set; }
        public virtual ICollection<WeeklyPlan> WeeklyPlan { get; set; }
    }
}
