//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int QuotationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Cavities { get; set; }
        public Nullable<decimal> RunnerWeight { get; set; }
        public Nullable<decimal> MetalContent { get; set; }
        public Nullable<decimal> MetalPrice { get; set; }
        public Nullable<decimal> MetalTotal { get; set; }
        public Nullable<decimal> Electricity { get; set; }
        public Nullable<decimal> ElectricityTotal { get; set; }
        public Nullable<decimal> Gas { get; set; }
        public Nullable<decimal> GasTotal { get; set; }
        public Nullable<decimal> GeneralExpenses { get; set; }
        public Nullable<decimal> GeneralExpensesCastingCount { get; set; }
        public Nullable<decimal> GeneralExpensesTotal { get; set; }
        public Nullable<decimal> Caster { get; set; }
        public Nullable<decimal> CasterCastingCount { get; set; }
        public Nullable<decimal> CasterTotal { get; set; }
        public Nullable<decimal> Fettler { get; set; }
        public Nullable<decimal> FettlerCastingCount { get; set; }
        public Nullable<decimal> FettlerTotal { get; set; }
        public Nullable<decimal> TotalCastingCost { get; set; }
        public Nullable<decimal> Drilling { get; set; }
        public Nullable<decimal> Tapping { get; set; }
        public Nullable<decimal> Turning { get; set; }
        public Nullable<decimal> Milling { get; set; }
        public Nullable<decimal> Threading { get; set; }
        public Nullable<decimal> TotalMachineryCost { get; set; }
        public Nullable<decimal> Sandblasting { get; set; }
        public Nullable<decimal> SandblastingCastingCount { get; set; }
        public Nullable<decimal> SandblastingTotal { get; set; }
        public Nullable<decimal> CoreMaker { get; set; }
        public Nullable<decimal> CoreMakerCoreCount { get; set; }
        public Nullable<decimal> CoreMakerTotal { get; set; }
        public Nullable<decimal> CoreRemover { get; set; }
        public Nullable<decimal> CoreRemoverCastingCount { get; set; }
        public Nullable<decimal> CoreRemoverTotal { get; set; }
        public Nullable<decimal> SandUsed { get; set; }
        public Nullable<decimal> SandPrice { get; set; }
        public Nullable<decimal> SandTotal { get; set; }
        public Nullable<decimal> TotalSandCost { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<decimal> PercentageDifference { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> StandardPercentage { get; set; }
    
        public virtual Casting Casting { get; set; }
        public virtual Company Company { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
