//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnToSupplier
    {
        public int ReturnToSupplierID { get; set; }
        public Nullable<int> ExternalCustomerID { get; set; }
        public Nullable<int> InternalCustomerID { get; set; }
        public string To { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> CastingID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
