//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialCasting
    {
        public int SpecialCastingId { get; set; }
        public Nullable<int> OldCastingID { get; set; }
        public Nullable<bool> SandCasting { get; set; }
        public Nullable<bool> SandCore { get; set; }
        public Nullable<bool> SandBlasted { get; set; }
        public Nullable<bool> BrassInsert { get; set; }
        public Nullable<bool> AluminiumInsert { get; set; }
        public Nullable<bool> StainlessSteelInsert { get; set; }
        public Nullable<bool> Hydraulics { get; set; }
        public Nullable<bool> HeatTreated { get; set; }
        public Nullable<bool> SandCup { get; set; }
        public Nullable<int> CupsFixed { get; set; }
        public Nullable<int> CupsLoose { get; set; }
        public Nullable<int> Cores { get; set; }
        public Nullable<int> CoresCollapsible { get; set; }
        public Nullable<int> BaseLoose { get; set; }
        public Nullable<int> BaseFixed { get; set; }
        public Nullable<int> DiePieces { get; set; }
        public Nullable<int> KnockOutPins { get; set; }
        public Nullable<int> Pins { get; set; }
        public Nullable<int> Wedges { get; set; }
        public Nullable<int> Slides { get; set; }
        public Nullable<int> ClampsQty { get; set; }
        public string ClampsSize { get; set; }
        public Nullable<int> HammersQty { get; set; }
        public string HammersSize { get; set; }
        public Nullable<int> PryeBarsQty { get; set; }
        public string PryeBarsSize { get; set; }
        public Nullable<int> Forks { get; set; }
        public Nullable<int> Hooks { get; set; }
        public Nullable<int> Runners { get; set; }
        public Nullable<int> Water { get; set; }
        public Nullable<int> AirGuns { get; set; }
        public Nullable<int> Pliers { get; set; }
        public Nullable<bool> DieCoat34Used { get; set; }
        public string DieCoat34Where { get; set; }
        public Nullable<bool> DieCoat39Used { get; set; }
        public string DieCoat39Where { get; set; }
        public Nullable<bool> DieCoat140Used { get; set; }
        public string DieCoat140Where { get; set; }
        public Nullable<bool> DieCoat11Used { get; set; }
        public string DieCoat11Where { get; set; }
        public Nullable<bool> LubixOilUsed { get; set; }
        public string LubixOilWhere { get; set; }
        public Nullable<bool> OtherUsed { get; set; }
        public string OtherWhere { get; set; }
        public string CastingInstructions { get; set; }
        public string HeatingInstructions { get; set; }
        public string SprayingInstructions { get; set; }
        public string OtherInstructions { get; set; }
    
        public virtual Casting Casting { get; set; }
    }
}
