//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTake
    {
        public StockTake()
        {
            this.StockTakeLineItem = new HashSet<StockTakeLineItem>();
            this.StockTakeVarianceLineItem = new HashSet<StockTakeVarianceLineItem>();
        }
    
        public int StockTakeID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Finalized { get; set; }
    
        public virtual ICollection<StockTakeLineItem> StockTakeLineItem { get; set; }
        public virtual ICollection<StockTakeVarianceLineItem> StockTakeVarianceLineItem { get; set; }
    }
}
