//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Reports
    {
        public System.Guid ItemID { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public int Type { get; set; }
        public byte[] Content { get; set; }
        public Nullable<System.Guid> Intermediate { get; set; }
        public Nullable<System.Guid> SnapshotDataID { get; set; }
        public Nullable<System.Guid> LinkSourceID { get; set; }
        public string Property { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public System.Guid CreatedByID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> SnapshotLimit { get; set; }
        public string Parameter { get; set; }
        public System.Guid PolicyID { get; set; }
        public bool PolicyRoot { get; set; }
        public int ExecutionFlag { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public string SubType { get; set; }
        public Nullable<System.Guid> ComponentID { get; set; }
    }
}
