//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyPlan
    {
        public int WeeklyPlanID { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Comments { get; set; }
    
        public virtual Casting Casting { get; set; }
        public virtual Company Company { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
